// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using webParser.Data;

#nullable disable

namespace webParser.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260426002325_AddParsedDataCache")]
    partial class AddParsedDataCache
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("webParser.Models.Database.AnalyzedField", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AnalyzedSiteId")
                        .HasColumnType("integer");

                    b.Property<int?>("FieldNameId")
                        .HasColumnType("integer");

                    b.Property<string>("FieldToGet")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AnalyzedSiteId");

                    b.HasIndex("FieldNameId");

                    b.ToTable("AnalyzedFields");
                });

            modelBuilder.Entity("webParser.Models.Database.AnalyzedSite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AnalyzedSites");
                });

            modelBuilder.Entity("webParser.Models.Database.FavoriteSite", b =>
                {
                    b.Property<int>("AnalyzedSiteId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("AnalyzedSiteId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("FavoriteSites");
                });

            modelBuilder.Entity("webParser.Models.Database.FieldName", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.HasKey("Id");

                    b.ToTable("FieldNames");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Цена"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Год выпуска"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Марка"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Модель"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Пробег"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Мощность двигателя"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Объём двигателя"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Тип топлива"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Коробка передач"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Привод"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Цвет"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Кузов"
                        });
                });

            modelBuilder.Entity("webParser.Models.Database.ParsedData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Field")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SiteId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SiteId");

                    b.ToTable("ParsedData");
                });

            modelBuilder.Entity("webParser.Models.Database.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Пользователь"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Редактор"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Администратор"
                        });
                });

            modelBuilder.Entity("webParser.Models.Database.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            Login = "admin",
                            Password = "admin",
                            RoleId = 3
                        });
                });

            modelBuilder.Entity("webParser.Models.Database.AnalyzedField", b =>
                {
                    b.HasOne("webParser.Models.Database.AnalyzedSite", null)
                        .WithMany()
                        .HasForeignKey("AnalyzedSiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("webParser.Models.Database.FieldName", null)
                        .WithMany()
                        .HasForeignKey("FieldNameId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("webParser.Models.Database.AnalyzedSite", b =>
                {
                    b.HasOne("webParser.Models.Database.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("webParser.Models.Database.FavoriteSite", b =>
                {
                    b.HasOne("webParser.Models.Database.AnalyzedSite", null)
                        .WithMany()
                        .HasForeignKey("AnalyzedSiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("webParser.Models.Database.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("webParser.Models.Database.ParsedData", b =>
                {
                    b.HasOne("webParser.Models.Database.AnalyzedSite", null)
                        .WithMany()
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("webParser.Models.Database.User", b =>
                {
                    b.HasOne("webParser.Models.Database.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
